# Generated by Django 4.2.15 on 2024-08-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='framesbatch',
            name='detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='framesbatch',
            name='detections',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
