# Generated by Django 4.2.15 on 2024-08-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='framesbatch',
            name='ball_job_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='framesbatch',
            name='objs_job_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
