# Generated by Django 4.2.15 on 2024-09-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_videoupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoupload',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='videoupload',
            name='file_size',
        ),
    ]
