# Generated by Django 4.2.15 on 2024-09-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_videoupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
