# Generated by Django 4.2.15 on 2024-09-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videoupload_uploaded_videoupload_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='objects_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='objects_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
