# Generated by Django 4.2.15 on 2024-09-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_videoupload_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='trim_page_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
