services:
  frontend:
    build:
      context: ../art-of-tennis
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_SERVER_SIDE_BACKEND_HOST=backend
      - NEXT_PUBLIC_CLIENT_SIDE_BACKEND_HOST=localhost
      - NEXT_PUBLIC_BACKEND_PORT=8000
    env_file:
      - .env.local
    volumes:
      - ../:/app 
  celery:
    build:
      context: ../../backend/tennis
      dockerfile: Dockerfile
      target: dev
    command: /home/django/.local/bin/celery -A artoftennis worker -l info
    volumes:
      - ../../backend/:/app
    depends_on:
      - backend
      - redis
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=db_user
      - DATABASE_PASSWORD=db_password
      - DATABASE_NAME=tennis
      - DATABASE_PORT=5432
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFeZ/f1RZyueT6SLG6WTyHJQ1hvvlk=;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - AZURE_STORAGE_CONTAINER_NAME=media
      - AZURE_STATIC_CONTAINER_NAME=static
      - PYTHONUNBUFFERED=1
      # - IS_PROD=False 
    env_file:
      - .env.local
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - art_of_tennis_redis_data_front:/data
  backend:
    build:
      context: ../../backend/tennis
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=db_user
      - DATABASE_PASSWORD=db_password
      - DATABASE_NAME=tennis
      - DATABASE_PORT=5432
      - PYTHONUNBUFFERED=1
      # - IS_PROD=False
    env_file:
      - .env.local
    volumes:
      - ../../backend/:/app
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:alpine3.19
    environment:
      POSTGRES_DB: tennis
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    volumes:
      - art_of_tennis_postgres_front:/var/lib/postgresql/data
volumes:
  art_of_tennis_postgres_front:
  art_of_tennis_redis_data_front:
