# Generated by Django 4.2.15 on 2024-08-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_trimspage_userpage_trimpage_framepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='framepage',
            name='detections',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
