# Generated by Django 4.2.15 on 2024-08-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_frame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frame',
        ),
    ]
