# Generated by Django 4.2.15 on 2024-08-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_framepage_detections'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimpage',
            name='trimming',
            field=models.BooleanField(default=False),
        ),
    ]
