# Generated by Django 4.2.15 on 2024-09-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_trimpage_trimming'),
    ]

    operations = [
        migrations.AddField(
            model_name='framepage',
            name='frame_number',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
