# Generated by Django 4.2.15 on 2024-08-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimpage',
            name='ball_job_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trimpage',
            name='frames_dir',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trimpage',
            name='objs_job_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
