# Generated by Django 4.2.15 on 2024-08-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_trimpage_ball_job_id_trimpage_frames_dir_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frame',
        ),
    ]
