# Generated by Django 4.2.15 on 2024-08-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trimpage',
            name='ball_job_id',
        ),
        migrations.RemoveField(
            model_name='trimpage',
            name='frames_dir',
        ),
        migrations.RemoveField(
            model_name='trimpage',
            name='objs_job_id',
        ),
    ]
